version: '3.8'

services:
  ai-backend:
    image: ${{ secrets.REGISTRY_USER }}/teamsync-ai-backend:${TAG:-latest}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - teamsync_network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  teamsync_network:
    external:
      name: teamsync_network
