name: Build & Deploy AI Backend

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_and_deploy:
    name: Build & Deploy AI Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build & Push Docker Image
        run: |
          TAG=${{ github.sha }}
          IMAGE=${{ secrets.REGISTRY_USER }}/teamsync-ai-backend
          docker build -f Dockerfile -t $IMAGE:${TAG} .
          docker push $IMAGE:${TAG}
          docker tag  $IMAGE:${TAG} $IMAGE:latest
          docker push $IMAGE:latest

      - name: SSH & Deploy on VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host:     ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     22
          script: |
            set -eux

            TAG=${{ github.sha }}
            IMAGE=${{ secrets.REGISTRY_USER }}/teamsync-ai-backend

            cat > /root/firebase-creds.json <<EOF
            ${{ secrets.FIREBASE_SA_KEY }}
            EOF

            # ensure the shared network exists
            docker network inspect teamsync_network \
              || docker network create teamsync_network

            # pull the new image (or fallback to latest)
            docker pull $IMAGE:${TAG} || docker pull $IMAGE:latest

            # remove old container
            old=$(docker ps -aq --filter "name=teamsync-ai-backend")
            if [ -n "$old" ]; then
              docker rm -f $old
            fi

            # run the new container, injecting secrets as env
            docker run -d \
              --name teamsync-ai-backend \
              --network teamsync_network \
              -p 8000:8000 \
              -v /root/firebase-creds.json:/app/firebase-creds.json:ro \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-creds.json \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
              -e DEEPSEEK_API_KEY="${{ secrets.DEEPSEEK_API_KEY }}" \
              -e QUADRANT_URL="${{ secrets.QUADRANT_URL }}" \
              -e QUADRANT_API_KEY="${{ secrets.QUADRANT_API_KEY }}" \
              -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              -e PROJECT_ID="${{ secrets.PROJECT_ID }}" \              
              $IMAGE:${TAG}
